package joincode

var adjectives = []string{
	"amber", "ancient", "autumn", "azure", "bitter",
	"bold", "brave", "bright", "broken", "bronze",
	"calm", "careful", "clever", "cold", "cool",
	"coral", "cosmic", "cozy", "crimson", "crystal",
	"dark", "dawn", "deep", "dusty", "early",
	"east", "easy", "empty", "fair", "falling",
	"faint", "fast", "final", "floral", "flying",
	"foggy", "free", "fresh", "frosty", "gentle",
	"global", "golden", "green", "happy", "hidden",
	"hollow", "humble", "icy", "inner", "iron",
	"jade", "jolly", "keen", "kind", "late",
	"lazy", "light", "little", "lively", "lone",
	"long", "lost", "lucky", "lunar", "misty",
	"modern", "morning", "muted", "noble", "north",
	"odd", "old", "open", "orange", "outer",
	"pale", "patient", "plain", "polar", "proud",
	"purple", "quick", "quiet", "rapid", "rare",
	"red", "rocky", "rough", "royal", "ruby",
	"rustic", "sandy", "scarlet", "secret", "sharp",
	"silent", "silver", "simple", "small", "smooth",
	"snowy", "soft", "solar", "solid", "south",
	"spring", "stable", "stark", "steady", "steep",
	"still", "stormy", "strong", "summer", "sunset",
	"sweet", "swift", "tall", "teal", "tender",
	"thin", "tidy", "tiny", "torn", "tough",
	"twin", "urban", "vast", "velvet", "warm",
	"west", "white", "wild", "winter", "wise",
	"witty", "wooden", "young", "zesty", "zippy",
}

var nouns = []string{
	"anchor", "apple", "arrow", "autumn", "badge",
	"beach", "bear", "bell", "bird", "bloom",
	"boat", "book", "branch", "breeze", "bridge",
	"brook", "canyon", "castle", "cave", "cedar",
	"cherry", "cliff", "cloud", "coast", "coral",
	"creek", "crown", "crystal", "dawn", "delta",
	"desert", "dove", "dream", "drift", "dune",
	"eagle", "earth", "ember", "falcon", "fern",
	"field", "flame", "flower", "forest", "fox",
	"frost", "garden", "gate", "glade", "glacier",
	"grove", "harbor", "hawk", "heart", "hill",
	"hollow", "horizon", "island", "jade", "lake",
	"leaf", "light", "lily", "lion", "maple",
	"marsh", "meadow", "mist", "moon", "moss",
	"mountain", "night", "oak", "ocean", "olive",
	"orchid", "owl", "palm", "path", "pebble",
	"peak", "pearl", "phoenix", "pine", "plain",
	"planet", "pond", "prairie", "rain", "raven",
	"reef", "ridge", "river", "robin", "rock",
	"rose", "sage", "sand", "shadow", "shore",
	"sky", "snow", "spark", "spring", "star",
	"stone", "storm", "stream", "summit", "sun",
	"thunder", "tide", "tiger", "trail", "tree",
	"tulip", "valley", "vine", "violet", "wave",
	"willow", "wind", "winter", "wolf", "wood",
}
